/*
 * configForm.java
 *
 * Created on 30 styczeñ 2007, 17:46
 */

package jadacz;

/**
 * Configuration window,
 * @author  Cyber
 */
public class configForm extends javax.swing.JFrame {

    /** True if user change properties */
    private boolean change = false;
    
    /** Instance of JXMLConfig object */
    private static JXMLConfig conf = null;
    
    /** Creates new form configForm */
    public configForm() {
        this.conf = JXMLConfig.getInstance();
        System.out.println(this.conf);  
        java.awt.Point p = new java.awt.Point();
        try{
            p = (java.awt.Point) conf.getFrameAttrib("configFormCocation");
            this.setLocation(p.x,p.y);
        }catch(java.lang.NullPointerException npe){
            conf.setProperty("configFormCocation",this.getX()+","+this.getY());
        }
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToggleButton2 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hostname = new javax.swing.JTextField();
        hostname.setText(conf.getProperty("server","127.0.0.1"));
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JID = new javax.swing.JTextField();
        JID.setText(conf.getProperty("userjid","0"));
        jLabel2 = new javax.swing.JLabel();
        JPass = new javax.swing.JPasswordField();
        JPass.setText(conf.getProperty("userpass",""));
        jLabel3 = new javax.swing.JLabel();
        storePassword = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jToggleButton2.setText("jToggleButton2");

        setIconImage(setIconImage());
        setName("configFrame");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                SaveWindowPosition(evt);
            }
        });

        getAccessibleContext().setAccessibleName("configForm");
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setText("Adres serwera:");

        hostname.setFont(new java.awt.Font("Tahoma", 0, 12));
        hostname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        hostname.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hostnamePropertyChange(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel5.setText("eg. 10.0.13.123");

        jLabel6.setText("Podaj adres serwera sieci Jadacz z kt\u00f3rym ma sie \u0142\u0105czy\u0107 klient.");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel5)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(hostname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jLabel6)
                .add(32, 32, 32)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(hostname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Po\u0142\u0105czenie", jPanel2);

        jLabel1.setText("Numer JID:");

        JID.setFont(new java.awt.Font("Tahoma", 0, 14));
        JID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JIDPropertyChange(evt);
            }
        });

        jLabel2.setText("Has\u0142o:");

        JPass.setFont(new java.awt.Font("Tahoma", 1, 12));
        JPass.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JPass.setDragEnabled(true);
        JPass.setEchoChar('\u00a4');
        JPass.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JPassPropertyChange(evt);
            }
        });

        jLabel3.setText("Wprowad\u017a sw\u00f3j numer identyfikacyjny oraz has\u0142o aby m\u00f3c po\u0142\u0105czy\u0107 si\u0119 z sieci\u0105 Jadacz");

        storePassword.setText("pami\u0119taj has\u0142o");
        storePassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        storePassword.setMargin(new java.awt.Insets(0, 0, 0, 0));
        if(conf.getProperty("storepass","true").equals("true")){
            storePassword.setSelected(true);
        }else{
            storePassword.setSelected(false);
        }
        storePassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                storePasswordPropertyChange(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(storePassword)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(JPass)
                            .add(JID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 211, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel3)
                .add(24, 24, 24)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(JID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(JPass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(storePassword)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("U\u017cytkownik", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Anuluj");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)))
        );

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /** 
     * Save window position to config
     * @see JXMLConfig#setProperty
     */
    private void SaveWindowPosition(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SaveWindowPosition
        int[] loc = new int[2];
        loc[0] = this.getX();
        loc[1] = this.getY();
        conf.setProperty("configFormCocation",loc[0]+","+loc[1]);
               
    }//GEN-LAST:event_SaveWindowPosition
    /**
     * Set up config and store it to XMLFile
     * @see JXMLConfig#setProperty 
     * @see JXMLConfig#storeToXML
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.change){
            conf.setProperty("server",this.hostname.getText());
            conf.setProperty("userjid",this.JID.getText());
            if(this.storePassword.isSelected()){
                System.out.println("dodaj haslo");
                String pass = null;
                pass = pass.copyValueOf(this.JPass.getPassword());
                System.out.println(pass.toString());
                conf.setProperty("userpass",pass);
                conf.setProperty("storepass","true");
            }else{
                conf.setProperty("userpass","");
                conf.setProperty("storepass","false");
            }

            conf.storeToXML();
            this.setVisible(false);
        }else{
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * If store password changed set up change semafor
     */
    private void storePasswordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_storePasswordPropertyChange
        this.change = true;
    }//GEN-LAST:event_storePasswordPropertyChange
    /**
     * If password changed set up change semafor
     */
    private void JPassPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JPassPropertyChange
        this.change = true;
    }//GEN-LAST:event_JPassPropertyChange
    /**
     * If jid changed set up change semafor
     */
    private void JIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JIDPropertyChange
        this.change = true;
    }//GEN-LAST:event_JIDPropertyChange
    /**
     * If hostname changed set up change semafor
     */
    private void hostnamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hostnamePropertyChange
       this.change = true;
    }//GEN-LAST:event_hostnamePropertyChange
    /**
     * Hide window
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new configForm().setVisible(true);
            }
        });
    }
    /**
     * Set up window icon
     */
    private java.awt.Image setIconImage(){
        
        java.io.File ico = new java.io.File("./icon.gif");
        return java.awt.Toolkit.getDefaultToolkit().getImage(ico.getAbsolutePath());
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JID;
    private javax.swing.JPasswordField JPass;
    private javax.swing.JTextField hostname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JCheckBox storePassword;
    // End of variables declaration//GEN-END:variables
    
}
