/*
 * fileSending.java
 *
 * Created on 10 luty 2007, 21:07
 */

package jadacz;

import jadacz.lib.FileInfo;

/**
 *
 * @author  Cyber
 */
public class FileSending extends javax.swing.JFrame {
    
    private int adapter;
    /** Creates new form fileSending */
    public FileSending() {
        initComponents();
    }
    public FileSending(FileInfo _file,int adp) {
        if(adp == 1){
            this.setTitle("Odbieranie pliku.");
        }else{
            this.setTitle("Wysy³anie pliku.");
        }
        this.adapter = adp;
        initComponents();
        fileName.setText(_file.getFilename());
        progressKB.setText(String.valueOf(0)+" KB");
        fileSize.setText(String.valueOf(_file.getFilesize()/1024)+" KB");
    }
    
    public void setTransferStatus(double procent, long size) {
        progressBar.setValue((int)procent);
        progressKB.setText(String.valueOf(size));
    }
    
    public void setEnd() {
        cancelButton.setText("OK");
        UserConnection uconn = (UserConnection) Registry.registry("uconn");
        if (this.adapter == 1) { // when receiving file
            uconn.sendFileTransferCancel();
            uconn.stopFileRecive();
        } else { // when sending file
            uconn.stopFileSend(0);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        progressBar = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();
        progressKB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        senderName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fileSize = new javax.swing.JLabel();

        setTitle("Wysy\u0142anie/Odbieranie pliku");
        setResizable(false);
        progressBar.setForeground(new java.awt.Color(153, 153, 153));

        cancelButton.setText("Anuluj");
        cancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        progressKB.setForeground(new java.awt.Color(102, 102, 102));
        progressKB.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Plik:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("U\u017cytkownik: ");

        jLabel3.setText("Rozmiar :");

        jLabel4.setText("Post\u0119p :");

        fileSize.setText("jLabel5");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 308, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fileName))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senderName))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, progressKB)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, fileSize))
                        .add(123, 123, 123)
                        .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(senderName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(fileName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(fileSize))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(cancelButton))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(progressKB))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileSending().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fileName;
    private javax.swing.JLabel fileSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressKB;
    private javax.swing.JLabel senderName;
    // End of variables declaration//GEN-END:variables
    
}
