/*
 * loginForm.java
 *
 * Created on 14 luty 2007, 23:44
 */

package jadacz;

import jadacz.lib.LoginRequest;
import java.security.spec.MGF1ParameterSpec;

/** 
 * Loggin form called if application can't find userjid and password or on user demand
 * @author  Cyber
 */

public class LoginForm extends javax.swing.JFrame {

    private mainGUI mg = null;
    /** Creates new form loginForm */
    public LoginForm() {
        initComponents();
        mg = (mainGUI) Registry.registry("maingui");
        System.out.println("LoginForm COnstruct");
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userJID = new javax.swing.JTextField();
        userPass = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        register = new javax.swing.JLabel();

        setTitle("Logowanie");
        jLabel1.setText("Wpisz sw\u00f3j numer u\u017cytkownika i has\u0142o \u017ceby si\u0119 zalogowa\u0107 do systemu.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setText("Logowanie");

        jLabel3.setText("Numer u\u017cytkownika:");

        jLabel4.setText("Has\u0142o:");

        userJID.setFont(new java.awt.Font("Tahoma", 0, 14));
        userJID.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userPass.setFont(new java.awt.Font("Tahoma", 0, 14));
        userPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cancelButton.setText("Anuluj");
        cancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        register.setForeground(new java.awt.Color(0, 0, 153));
        register.setText("Zarejestruj si\u0119");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)))
                    .add(layout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(layout.createSequentialGroup()
                                .add(62, 62, 62)
                                .add(jLabel4)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(userPass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .add(userJID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .add(63, 63, 63))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(register)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 156, Short.MAX_VALUE)
                .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(16, 16, 16)
                .add(jLabel1)
                .add(32, 32, 32)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(userJID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(userPass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(okButton)
                    .add(register))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Show registration window and hide login form
     */
    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        new RegistrationForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerMouseClicked
    /**
     * Save login information to config and send login request
     * @see UserConnection#sendLoginRequest
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        JXMLConfig conf = (JXMLConfig) Registry.registry("conf");
        conf.setProperty("userjid",userJID.getText());
        conf.setProperty("userpass",userPass.getText());
        conf.storeToXML();
        //mainGUI mg = (mainGUI) Registry.registry("maingui");
       // mg.serverConnect();
        LoginRequest lr = new LoginRequest();
        lr.setJID(Integer.valueOf(userJID.getText()));
        lr.setPassword(userPass.getText());
        lr.setVersion((float)0.002);

        mg.serverConnect();
        UserConnection uconn = (UserConnection) Registry.registry("uconn");
        uconn.sendLoginRequest(lr);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    /**
     * Dispose loginform window
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("LoginForm main");
                new LoginForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel register;
    private javax.swing.JTextField userJID;
    private javax.swing.JTextField userPass;
    // End of variables declaration//GEN-END:variables
    
}
